### PR TITLE
Added a installation script that can be curled

### PR DESCRIPTION
**Pull request by dyegoaurelio**
With this pr, we'll be able to install this theme with only one command!
simply run 
`curl -s -o- https://raw.githubusercontent.com/dyegoaurelio/firefox-gnome-theme/curlscript/scripts/install-by-curl.sh | bash`
(when the pr is accepted just change dyegoaurelio/firefox-gnome-theme/curlscript for rafaelmardojai/firefox-gnome-theme/master from the curl command )
Captura de tela de 2020-10-23 12-22-42

### CODE REVIEW

**Comment by rafaelmardojai** [comment]
I'm not a fan of encouraging copy-pasting and running random scripts online, but I'm fine adding this as an alternative.

**Comment by dyegoaurelio** [comment]
I really liked this theme, and my goal with this pr is to provide a more practical installation so more people could use it
I intended to this curl command to be available on README.md, thought I understand your point, since people would find this command on this repository and would curl a script which is also located in this repository, I cant see no harm.

**Comment by rafaelmardojai** [comment]
Later I will update the README.

**Comment by dyegoaurelio** [comment]
Nice!
And a new release is also needed for the curl script to get the newest features.

**Comment by rafaelmardojai** [comment]
>  And a new release is also needed for the curl script to get the newest features.

Yeah, I just need to update to Firefox 82, test everything is fine and release a new version.

**Comment by rafaelmardojai** [comment]
Just released a new version.

**Pull request merged**
