### PR TITLE
Only overwrite css where needed

### PR DESCRIPTION
**Pull request by razzeee**
This cleans up the maia and yaru themes like the comment here suggested https://github.com/rafaelmardojai/firefox-gnome-theme/issues/270#issuecomment-907639978

I only tested maia-dark, not sure how to do the other ones, this was done via git diff, so I'm quiet sure it should be fine.

### CODE REVIEW

**Comment by rafaelmardojai** [comment]
Yeah, looks fine. Has you tested it?

**Comment by rafaelmardojai** [comment]
Also I think that the only maia true change was the green accent color. Probably other differences are also because non updated changes.

**Comment by razzeee** [comment]
As stated above, I only tested Maia dark.

I don't know which of the changes are by design.

**Comment by rafaelmardojai** [comment]
That can be answered by @Chrysostomus if available.

**Comment by Chrysostomus** [comment]
Cleaning up code is good. Maia just tries to setup the accent colors green. But I don't actually know any css, so if yo uhave tested that it works, simplification is a boon.

**Comment by razzeee** [comment]
I had another look at the latest commits:
https://github.com/razzeee/firefox-gnome-theme/commit/074304622db66142075be2c27d33ba15df5207ec
https://github.com/rafaelmardojai/firefox-gnome-theme/commit/3a472717f1a442e07efefd7700212e542965c150
https://github.com/razzeee/firefox-gnome-theme/commit/bfe9f83d18019ada56045af6d29f8c53b8d43ca7

and inferred, which other variables could be removed. I've pushed a commit cleaning those up.
I did test maia dark and light (briefly)

**Review by CleoMenezes — APPROVED** [review]
Amazing!

**Review by rafaelmardojai — APPROVED** [review]

**Comment by rafaelmardojai** [comment]
Looks good to merge!

**Pull request merged**
