### PR TITLE
Fix symlink made from wrong directory to wrong directory

### PR DESCRIPTION
**Pull request by svito3**
At line 44 you do `cd chrome`, so you are located inside `chrome`.

### CODE REVIEW

**Comment by rafaelmardojai** [comment]
Firefox `user.js` goes directly in user profile folder not in `chrome` subfolder.

**Comment by rafaelmardojai** [comment]
But, your fix is more clean. So let's go that way.
Thanks.

**Comment by svito3** [comment]
> Couldn't be fixed with `ln -s firefox-gnome-theme/configuration/user.js ../user.js`?

It would result in a broken symlink: `user.js -> firefox-gnome-theme/configuration/user.js`. Our symbolic link uses a relative path that we have specified. It does not figure out the correct relative path depending on where we have placed symlink file nor does it care if the file we are linking to exists.

**Comment by rafaelmardojai** [comment]
Yeah, now i see. Thanks!

**Pull request merged**
