### PR TITLE
Add an OLED black theme

### PR DESCRIPTION
**Pull request by rstanuwijaya**
Added an OLED black theme (for OLED display)

image

### CODE REVIEW

**Review by BirdInFire — CHANGES_REQUESTED** [review]
As a disclaimer this review only talk about the code itself not the "idea" of oled version (which will be stated later in "conversation").

I actually find a major issue witch make me ask the refusal (if not modified) is the fact that this actual code will do nothing (as not loaded anywhere), and if a change is made to load it, it will override the normal dark theme.

So my request is : 

make a change to trigger it with an optional about:config settings
add it in a way it's actually loaded by the theme.

**Comment by BirdInFire** [comment]
So now my "PERSONAL" stance is : I don't really see the benefit of an oled version as libadwaita do not propose this actual "oled" color scheme.

**Comment by rstanuwijaya** [comment]
I updated the PR to address your requests

**Review by rafaelmardojai — APPROVED** [review]
LGTM!

**Pull request merged**
