### PR TITLE
Pop_Os! Theme

### PR DESCRIPTION
**Pull request by dyegoaurelio**
Starting to address #164

### CODE REVIEW

**Comment by rafaelmardojai** [comment]
This is what I implemented locally some time ago:

Change for `csd.css` L102:
```css
/* Window buttons box */
:root[tabsintitlebar] #titlebar .titlebar-buttonbox-container,
:root[tabsintitlebar][inFullscreen] #window-controls {
	-moz-appearance: none !important;
	align-items: center;
	justify-content: center;
	display: flex;
	height: 46px;
	padding: 0 3px;
	position: absolute !important;	
	right: 0;
	top: 0;
}
```

New optional feature:
```css
/* OPTIONAL: Use system window buttons */
@supports -moz-bool-pref("gnomeTheme.systemWindowButtons") {
	:root[tabsintitlebar] #titlebar .titlebar-button:not(#hack) {
		height: auto !important;
		width: auto !important;
		padding: 0  !important;
		margin: 0 !important;
	}	
	:root[tabsintitlebar] #titlebar .titlebar-button:hover:not(#hack) {
		box-shadow: none !important;
	}
	:root[tabsintitlebar] #titlebar .titlebar-buttonbox .toolbarbutton-icon:not(#hack) {
		list-style-image: none !important;
	}
	:root[tabsintitlebar] #titlebar .titlebar-button.titlebar-close:not(#hack) {
		-moz-appearance: -moz-window-button-close !important;
	}
	:root[tabsintitlebar] #titlebar .titlebar-button.titlebar-max:not(#hack) {
		-moz-appearance: -moz-window-button-maximize !important;
	}
	:root[tabsintitlebar] #titlebar .titlebar-button.titlebar-restore:not(#hack) {
		-moz-appearance: -moz-window-button-restore !important;
	}
	:root[tabsintitlebar] #titlebar .titlebar-button.titlebar-min:not(#hack) {
		-moz-appearance: -moz-window-button-minimize !important;
	}
	/* Window controls position */
	:root[tabsintitlebar] #titlebar .titlebar-buttonbox-container {
		width: var(--gnome-window-controls-spacing);
	}
	:root[tabsintitlebar]:not([inFullscreen]) #nav-bar {
		padding-right: var(--gnome-window-controls-spacing) !important;
	}
	@media (-moz-gtk-csd-reversed-placement) {
		:root[tabsintitlebar]:not([inFullscreen]) #nav-bar {
			padding-right: 3px !important;
		}
		:root[tabsintitlebar]:not([inFullscreen]) #nav-bar {
			padding-left: var(--gnome-window-controls-spacing) !important;
		}
	}
}
```

**Comment by rafaelmardojai** [comment]
Also like `csd.css` we will need to have different variables depending on the buttons number:

```css
/* Window buttons: at least 1 button */
@media (-moz-gtk-csd-minimize-button), (-moz-gtk-csd-maximize-button), (-moz-gtk-csd-close-button) {
	:root[tabsintitlebar]:not([inFullscreen]) #nav-bar {
		padding-right: var(--gnome-window-controls-spacing-1) !important;
	}
}
/* Window buttons: at least 2 buttons */
@media (-moz-gtk-csd-minimize-button) and (-moz-gtk-csd-maximize-button),
       (-moz-gtk-csd-minimize-button) and (-moz-gtk-csd-close-button),
       (-moz-gtk-csd-maximize-button) and (-moz-gtk-csd-close-button) {
	:root[tabsintitlebar]:not([inFullscreen]) #nav-bar {
		padding-right: var(--gnome-window-controls-spacing-2) !important;
	}
}
/* Window buttons: 3 buttons */
@media (-moz-gtk-csd-minimize-button) and (-moz-gtk-csd-maximize-button) and (-moz-gtk-csd-close-button) {
	:root[tabsintitlebar]:not([inFullscreen]) #nav-bar {
		padding-right: var(--gnome-window-controls-spacing-3) !important;
	}
}
```

And the same for `@media (-moz-gtk-csd-reversed-placement)`.

**Comment by dyegoaurelio** [comment]
With these new changes the title bar icons are working fine here. I'd like for someone else to test to see if works well too
Captura de tela de 2020-11-15 22-51-14
Captura de tela de 2020-11-15 22-51-01
Captura de tela de 2020-11-15 22-50-40

**Comment by rafaelmardojai** [comment]
Oh nice, I thought that Pop Os! title buttons had smaller margin between them.

**Comment by dyegoaurelio** [comment]
You're right, they are a little offset
I'll fix that
Captura de tela de 2020-11-15 23-10-59

**Comment by dyegoaurelio** [comment]
Maybe this setting should be coded on Pop theme itself

**Comment by dyegoaurelio** [comment]
Also it's missing the fade effect when the mouse hoover over the close button
and remove this straight line that appears on top of all icons when hoovered 
firefox icons
nauitilus

**Comment by rafaelmardojai** [comment]
> Also it's missing the fade effect when the mouse hoover over the close button

Those kind of issue are what made me implement it hardcoded. It also don't respect the window inactive state.

>  and remove this straight line that appears on top of all icons when hoovered

You can fix it with:
```css
:root[tabsintitlebar] #titlebar .titlebar-button:hover:not(#hack) {
	box-shadow: none !important;
}
```

**Comment by perin-lionshead** [comment]
Okay, I think I've got the colors pretty consistent - it should at least be a good starting point! I haven't really contributed before, what is the best way to share the new file? Just copy and paste?

**Comment by dyegoaurelio** [comment]
@perin-lionshead Cool!
I invited you as a collaborator on my fork
you need to aceppt the invite, and them push your changes to sys-title branch

**Comment by dyegoaurelio** [comment]
Or, if you're not familiar to git you can just copy paste here

**Comment by perin-lionshead** [comment]
I'm not familiar, but I think I can figure it out, which will be helpful in the future!

**Comment by perin-lionshead** [comment]
Do you care whether I do it as a direct commit or a pull request?

**Comment by dyegoaurelio** [comment]
@perin-lionshead I liked the colours but there are still blue elements on the search bar, and some header bar buttons bugs
Captura de tela de 2020-11-16 20-42-14
inaccurate icons when inactive

Peek 16-11-2020 20-43
no contrast when clicked (this works on default theme)

**Comment by perin-lionshead** [comment]
Yes, I see those! I actually changed the blue to match the pop blue highlight color as bit of pop (hehe), but I can change it for sure if you prefer! I will work on the inactive icons and contrast tomorrow - definitely itching to fix them now that you've pointed them out! I'll start on the light theme after I clear up those inconsistencies!

**Comment by dyegoaurelio** [comment]
Great!
You're right, the blue highlight makes total sense, but I think that the colour around the clicked search bar may look better as Orange. But it's up to you to decide

**Comment by rafaelmardojai** [comment]
What is left to merge it? I would like to merge this before releasing v83.

**Comment by perin-lionshead** [comment]
I think I just have to tweak a few colors!  @dyegoaurelio, you already fixed the buttons on hover right? So I am just doing the highlight color for the search box and the inactive window colors, right? I'll work on it right now and should have it done in an hour or so!

**Comment by dyegoaurelio** [comment]
Unfoe

**Comment by dyegoaurelio** [comment]
Unfortunately i cant work on this project this weekend, but I haven't fixed the hoover animation. I'd like to find a way to put the system native animation.

**Comment by dyegoaurelio** [comment]
So if someone turn on System Window Buttons, they will behave just like native buttons

**Comment by perin-lionshead** [comment]
No worries! I'll do my bit and fix the hover color as well, and then if you get to do the system buttons that will just be icing on the cake!

**Comment by perin-lionshead** [comment]
What version of Pop GTK theme are you using @dyegoaurelio? When I hover over my buttons in nautilus they get lighter and the same with other system apps - which I think is why I left the buttons lighter before, is it maybe that we are using different versions? Or maybe I have something weird going on with my system because I'm on Manjaro? I am on version 5.3.1!

**Comment by rafaelmardojai** [comment]
@dyegoaurelio If you want to have nice transitions, I suggest you to hardcode the title buttons styles and use CSS transition. Firefox native looking styles are a mess.

**Comment by dyegoaurelio** [comment]
unfortunely I wasnt able to neither hard code the hover animation or properly use the native one. 
the problem is in this line [https://github.com/rafaelmardojai/firefox-gnome-theme/blob/dfa1bc5cc289484449b6d09e0d17ec165a8e5aba/theme/parts/csd.css#L111](https://github.com/rafaelmardojai/firefox-gnome-theme/blob/dfa1bc5cc289484449b6d09e0d17ec165a8e5aba/theme/parts/csd.css#L111)

if I remove this display property, the transitions are flawless, but the buttons are stuck on the scrollbox and i cant move it 
if I leave as it is, I cant change the buttons hover properties

I guess I'll leave as it is :(

**Comment by dyegoaurelio** [comment]
unfortunely I wasnt able to neither hard code the hover animation or properly use the native one. 
the problem is in this line [https://github.com/rafaelmardojai/firefox-gnome-theme/blob/dfa1bc5cc289484449b6d09e0d17ec165a8e5aba/theme/parts/csd.css#L111](https://github.com/rafaelmardojai/firefox-gnome-theme/blob/dfa1bc5cc289484449b6d09e0d17ec165a8e5aba/theme/parts/csd.css#L111)

if I remove this display property, the transitions are flawless, but the buttons are stuck on the scrollbox and i cant move it 
if I leave as it is, I cant change the buttons hover properties

I guess I'll just let it stay with this hoover animation, it isnt that big of a deal

**Comment by dyegoaurelio** [comment]
Light theme isn't that perfect because Pop header bar is dark even on light theme, and I couldn't consistently turn all icons white.

But still looks cool to me

**Comment by dyegoaurelio** [comment]
I'm not particularly experienced with front-end and css, so this PR has been both fun and challenging. Thanks for all your help :)

**Comment by rafaelmardojai** [comment]
>  the problem is in this line 

Changing to `display : flex;` as it suggested in https://github.com/rafaelmardojai/firefox-gnome-theme/pull/173#issuecomment-727631470 doesn't help?

> Light theme isn't that perfect because Pop header bar is dark even on light theme, and I couldn't consistently turn all icons white.

If you want to have a different icon color in the headerbar, you can do something like this:
```css
:root[tabsintitlebar] #nav-bar .toolbarbutton-icon:not(#hack),
#titlebar .titlebar-button .toolbarbutton-icon:not(#hack),
:root[inFullscreen] #window-controls toolbarbutton:not(#hack) .toolbarbutton-icon:not(#hack),
#downloads-indicator-icon {
	fill: /* Color here */ !important;
}
```

**Comment by perin-lionshead** [comment]
Here is the new entry box color scheme for the dark theme! Don't know if you'd done that already! 

/* Entries */
		--gnome-entry-background: #404040;
		--gnome-entry-border-color: #272727;
		--gnome-entry-box-shadow: inset 0 0 0 1px rgba(21, 83, 158, 0);
		--gnome-entry-color: #ffffff;
		--gnome-inactive-entry-background: #363636;
		--gnome-inactive-entry-border-color: #434343;
		--gnome-inactive-entry-box-shadow: none;
		--gnome-inactive-entry-color: #d6d6d6;
		--gnome-focused-urlbar-border-color: #fbb86c;

**Comment by Blackrucat** [comment]
image
orange buttons doesn't seem to work.

**Comment by dyegoaurelio** [comment]
@Blackrucat interesting, which distro are you running?

**Comment by Blackrucat** [comment]
Pop!_OS!

**Comment by Blackrucat** [comment]
Sorry, actually i've forgotten about using  this:
https://github.com/rafaelmardojai/firefox-gnome-theme/pull/173#issuecomment-735029795

**Comment by Blackrucat** [comment]
Why don't you guys just drop a CSD.css
file, it would really help everyone, some people just want to install the theme, they don't want to be CSS coders haha.

**Comment by dyegoaurelio** [comment]
@Blackrucat as soon as we finish this pr, and its merged, the Pop theme will be installed by default on Pop Os machines

**Comment by dyegoaurelio** [comment]
Unfortunely recently I've been pretty busy, but Im plannig to finish this soon

**Comment by Blackrucat** [comment]
After a good time trying to do it, this worked for me. 

**csd.css** 

`/* GNOME CSD styles for headerbar on Firefox [tabsintitlebar] */

@namespace xul url("http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul");

#main-window {
	-moz-appearance: -moz-window-titlebar !important;
}

/* Headerbar top border corners rounded */
:root[tabsintitlebar]:not([inFullscreen]):not([sizemode="maximized"]) #nav-bar {
	border-radius: 7px 7px 0 0 !important;
}

/* Window buttons: at least 1 button */
@media (-moz-gtk-csd-minimize-button), (-moz-gtk-csd-maximize-button), (-moz-gtk-csd-close-button) {
	:root[tabsintitlebar]:not([inFullscreen]) #nav-bar {
		padding-right: 50px !important;
	}
}
/* Window buttons: at least 2 buttons */
@media (-moz-gtk-csd-minimize-button) and (-moz-gtk-csd-maximize-button),
       (-moz-gtk-csd-minimize-button) and (-moz-gtk-csd-close-button),
       (-moz-gtk-csd-maximize-button) and (-moz-gtk-csd-close-button) {
	:root[tabsintitlebar]:not([inFullscreen]) #nav-bar {
		padding-right: 90px !important;
	}
}
/* Window buttons: 3 buttons */
@media (-moz-gtk-csd-minimize-button) and (-moz-gtk-csd-maximize-button) and (-moz-gtk-csd-close-button) {
	:root[tabsintitlebar]:not([inFullscreen]) #nav-bar {
		padding-right: 130px !important;
	}
}

/* Left window buttons */
@media (-moz-gtk-csd-reversed-placement) {
	:root[tabsintitlebar]:not([inFullscreen]) #nav-bar {
		padding-right: 3px !important;
	}
	
	/* Window buttons box */
	:root[tabsintitlebar] #titlebar .titlebar-buttonbox-container {
		left: 0;
		right: auto !important;
	}

	/* Window controls: at least 1 button */
	@media (-moz-gtk-csd-minimize-button), (-moz-gtk-csd-maximize-button), (-moz-gtk-csd-close-button) {
		:root[tabsintitlebar]:not([inFullscreen]) #nav-bar {
			padding-left: 50px !important;
		}
	}
	/* Window controls: at least 2 buttons */
	@media (-moz-gtk-csd-minimize-button) and (-moz-gtk-csd-maximize-button),
				 (-moz-gtk-csd-minimize-button) and (-moz-gtk-csd-close-button),
				 (-moz-gtk-csd-maximize-button) and (-moz-gtk-csd-close-button) {
		:root[tabsintitlebar]:not([inFullscreen]) #nav-bar {
			padding-left: 90px !important;
		}
	}
	/* Window controls: 3 buttons */
	@media (-moz-gtk-csd-minimize-button) and (-moz-gtk-csd-maximize-button) and (-moz-gtk-csd-close-button) {
		:root[tabsintitlebar]:not([inFullscreen]) #nav-bar {
			padding-left: 130px !important;
		}
	} 
}

/* Fullscreen headerbar padding for 1 button */
:root[tabsintitlebar][inFullscreen] #nav-bar {
	padding-right: 50px !important;
}

/* Remove close and minimize buttons from fullscreen buttons */
:root[tabsintitlebar][inFullscreen] #window-controls #close-button,
:root[tabsintitlebar][inFullscreen] #window-controls #minimize-button,
:root[tabsintitlebar][inFullscreen] #titlebar .titlebar-buttonbox-container {
	display: none !important;
}

/* Remove tabsbar titlebar blank spaces */
:root[tabsintitlebar] #TabsToolbar .titlebar-placeholder {
	display: none !important;
}

/* Prevent menubar from breaking */
:root[tabsintitlebar] #toolbar-menubar:not([inactive=true]) {
	height: 30px !important;
	margin-bottom: 8px;
}

/* Remove default style of titlebar */
:root[tabsintitlebar] #titlebar {
	-moz-appearance: none !important;
}

/* Fix the issue when dragging tabs */
:root[tabsintitlebar] #navigator-toolbox[movingtab] #TabsToolbar {
	padding-bottom: 0 !important;
}

/* Window buttons box */
:root[tabsintitlebar] #titlebar .titlebar-buttonbox-container,
:root[tabsintitlebar] #titlebar-buttonbox-container,
:root[tabsintitlebar][inFullscreen] #window-controls {
	-moz-appearance: none !important;
	padding: 6px 3px;
	position: absolute !important;	
	right: 0;
	top: 0;
	display: block !important;
}
:root[tabsintitlebar] #titlebar .titlebar-buttonbox {
	-moz-appearance: none !important;
}

/* Window buttons style */
@supports -moz-bool-pref("gnomeTheme.systemWindowButtons") {
	:root[tabsintitlebar] #titlebar .titlebar-button:not(#hack) {
		height: auto !important;
		width: auto !important;
		padding: 0  !important;
		margin: 0 !important;
	}	
	:root[tabsintitlebar] #titlebar .titlebar-button:hover:not(#hack) {
		box-shadow: none !important;
	}
	:root[tabsintitlebar] #titlebar .titlebar-buttonbox .toolbarbutton-icon:not(#hack) {
		list-style-image: none !important;
	}
	:root[tabsintitlebar] #titlebar .titlebar-button.titlebar-close:not(#hack) {
		-moz-appearance: -moz-window-button-close !important;
	}
	:root[tabsintitlebar] #titlebar .titlebar-button.titlebar-max:not(#hack) {
		-moz-appearance: -moz-window-button-maximize !important;
	}
	:root[tabsintitlebar] #titlebar .titlebar-button.titlebar-restore:not(#hack) {
		-moz-appearance: -moz-window-button-restore !important;
	}
	:root[tabsintitlebar] #titlebar .titlebar-button.titlebar-min:not(#hack) {
		-moz-appearance: -moz-window-button-minimize !important;
	}
	/* Window controls position */
	:root[tabsintitlebar] #titlebar .titlebar-buttonbox-container {
		width: var(--gnome-window-controls-spacing);
	}
	:root[tabsintitlebar]:not([inFullscreen]) #nav-bar {
		padding-right: var(--gnome-window-controls-spacing) !important;
	}
	@media (-moz-gtk-csd-reversed-placement) {
		:root[tabsintitlebar]:not([inFullscreen]) #nav-bar {
			padding-right: 3px !important;
		}
		:root[tabsintitlebar]:not([inFullscreen]) #nav-bar {
			padding-left: var(--gnome-window-controls-spacing) !important;
		}
	}
}
}

:root[tabsintitlebar] #titlebar .titlebar-button {
	border-radius: 100% !important;
	height: 30px !important;
	margin: 2px 5px !important;
	width: 30px;
}

:root[tabsintitlebar][inFullscreen] #window-controls toolbarbutton {
	border-radius: 5px !important;
	height: 34px;
	margin: 0 3px !important;
	width: 34px;
}

:root[tabsintitlebar] #titlebar .titlebar-button .toolbarbutton-icon,
:root[tabsintitlebar][inFullscreen] #window-controls toolbarbutton .toolbarbutton-icon {
	width: 16px;
}
:root[tabsintitlebar] #titlebar:-moz-window-inactive .titlebar-button .toolbarbutton-icon,
:root[tabsintitlebar][inFullscreen] #window-controls:-moz-window-inactive toolbarbutton .toolbarbutton-icon {
	opacity: .3 !important;
}
:root[tabsintitlebar] #titlebar:not(:-moz-window-inactive) .titlebar-button:not([disabled]):hover,
:root[tabsintitlebar][inFullscreen] #window-controls:not(:-moz-window-inactive) toolbarbutton:not([disabled]):hover {
	background-image: var(--gnome-button-hover-background);
	border-color: var(--gnome-button-border-color) !important;
	border-bottom-color: var(--gnome-button-border-accent-color) !important;
	box-shadow: var(--gnome-button-box-shadow);
}
:root[tabsintitlebar] #titlebar:not(:-moz-window-inactive) .titlebar-button:not([disabled]):active,
:root[tabsintitlebar][inFullscreen] #window-controls:not(:-moz-window-inactive) toolbarbutton:not([disabled]):active {
	background: var(--gnome-button-active-background);
	box-shadow: var(--gnome-button-active-box-shadow);
	border-color: var(--gnome-button-active-border-color) !important;
}
`

**Comment by dyegoaurelio** [comment]
I'm no longer using Pop_Os and also can't find much free time to finish this PR, so I'm closing it :(
Anyone interested on finishing it fell free to do so.

**Pull request closed without merging**
