### PR TITLE
Install by cUrl improvements

### PR DESCRIPTION
**Pull request by dyegoaurelio**
With this pr, the cUrl installation script will be able to look for Firefox installation folders and the current system theme.

### CODE REVIEW

**Comment by rafaelmardojai** [comment]
Awesome! 

I think this will be very useful aside the cUrl installation method. 
Maybe we can move it to another script?

**Comment by dyegoaurelio** [comment]
Created an auto-install script, hence now we can easily locally install the theme, but still open for the custom install option

**Comment by dyegoaurelio** [comment]
Created an auto-install script, hence now we can easily locally install the theme, but we're still able to perform a  custom install with install.sh script

**Comment by dyegoaurelio** [comment]
this push will break install-by-curl until next release

**Comment by rafaelmardojai** [comment]
Nice work! Thanks for taking the time.

> this push will break install-by-curl until next release

I'm going to release a new version in next days, hoping we can merge #173 before.

**Comment by rafaelmardojai** [comment]
Would be good to also add the new Manjaro color scheme `maia` to the script.

@Chrysostomus what are the installation names of the `maia` themes?

**Comment by Chrysostomus** [comment]
Adwaita-maia and Adwaita-maia-dark.

In packaged version, I have been installing the Firefox theme under /usr/share/themes and shipping alternative install script that symlimks the directory to users Firefox profile. That's how we have kept it up to date for users without having to edit their files with package manager. The downside is that it is not easy to edit for users.

**Comment by dyegoaurelio** [comment]
Keeping the theme folder on /themes is a good idea. It makes updating easier.
We could do something like this in the install script later

**Comment by dyegoaurelio** [comment]
I downloaded manjaro and the default theme was Matcha-sea
Should we enable the maia theme for Matcha-sea users as well?

**Comment by Chrysostomus** [comment]
Maybe not, default firefox theme is more consisntent with matcha-sea. Manjaro comes with optional theme adwaita-maia, which is compatible with this firefox theme. We might switch to defaulting to adwaita-maia later though. 

If you are interested, this is my install script, shipped with the manjaro installation:

https://gitlab.manjaro.org/Chrysostomus/firefox-gnome-theme-maia/-/blob/master/scripts/firegnome-enable.sh

**Comment by dyegoaurelio** [comment]
solves #185

**Pull request merged**
