### PR TITLE
Added gnomeTheme.noThemedIcons

### PR DESCRIPTION
**Pull request by jaydenlo08**
Added a way to allow original icons from Firefox to be used

### CODE REVIEW

**Review by BirdInFire — CHANGES_REQUESTED** [review]
This pull request miss in the readme.md under Enabling optional features, the name of the switch and what he does (if not documented nobody will know it exist).

Also @rafaelmardojai need (to check if it actually working), nothing personal but with the increasing number of AI made pull request It must be checked.

**Comment by jaydenlo08** [comment]
Just updated the README.

Sorry if this PR looks a bit hacky - I initially didn't intend to make this public, just thought might be a good idea to contribute back.

I haven't really opened PRs before so please tell me if I'm doing anything wrong

**Comment by BirdInFire** [comment]
> Just updated the README.
> 
> Sorry if this PR looks a bit hacky - I initially didn't intend to make this public, just thought might be a good idea to contribute back.
> 
> I haven't really opened PRs before so please tell me if I'm doing anything wrong

Ahah it's exactly how I started maintaining the vertical tab at first it was 3 hack patched together with time I used myself the toolbox of firefox to make it properly xD

And I had also forgotten the readme (why I told you since I had the same error at my first here).

**Review by rafaelmardojai — CHANGES_REQUESTED** [review]
Hi, thanks for contributing.

Code looks good overall, I will give it a try in the weekend.

The only problem I found now is that you're not using tabs for indentation, I may standardize the CSS style in the future and maybe move to using spaces, but for now please use tabs to be consistent with the document.

**Comment by jaydenlo08** [comment]
Kinda left this hanging for months - fixed some small bug related to the CSD

**Comment by rafaelmardojai** [comment]
Sorry, could you do a clean rebase? Doing a review with so many commits on it is a bit confusing.

**Comment by jaydenlo08** [comment]
Sorry for asking this seemingly stupid question, but how do I do so? I am relatively new to the git and contributing world...
My branch looks like this now (taken from gitg - sorry if it looks like a nightmare)
image

**Comment by jaydenlo08** [comment]
Hi Rafael, I think I may have just done a "clean rebase"  after lots of experimenting (and learning). Hopefully it's much more reading now

**Review by rafaelmardojai — APPROVED** [review]

**Comment by rafaelmardojai** [comment]
Thanks a lot!

**Pull request merged**
